[general]
live_config_reload=true

[window]
opacity=0.85
padding={x=10,y=10}
decorations = "None"

[scrolling]
history=10000
multiplier=5

[font]
normal={family="Inconsolata Nerd Font Mono",style="bold"}
size=10

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"
