[general]
import = [
"~/.config/alacritty/themes/themes/dracula.toml"
]
live_config_reload=true

[window]
padding={x=5,y=5}
decorations = "None"
[scrolling]
history=10000
multiplier=5

[font]
normal={family="Hack Nerd Font Mono",style="Bold"}
size=8

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"
