[general]
import = [
"~/.config/alacritty/themes/themes/dracula.toml"
]
live_config_reload=true

[window]
padding={x=10,y=10}
decorations = "None"
opacity= 0.75
blur=true

[scrolling]
history=10000
multiplier=5

[font]
normal={family="GeistMono Nerd Font",style="Medium"}
size=8

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"
